/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agendasencilla;

import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Asus
 */
public class Pantalla extends javax.swing.JFrame {

    public Connection conectar() {
        String usuario = "root";
        String contrasena = "";
        String url = "jdbc:mysql://localhost:3306/agenda";
        Connection con = null;
        try {
            con = DriverManager.getConnection(url, usuario, contrasena);
            salida.setText("Conexión correcta");
            return con;
        } catch (Exception e) {
            salida.setText("Conexión incorrecta");
            return null;
        }
    }

    //modelo para manipular la tabla
    DefaultTableModel modelo;

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();

        //inicio el modelo para manipular la tabla
        modelo = (DefaultTableModel) tabla.getModel();

        // Mostrar líneas de la tabla
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);

        // Color de las líneas
        tabla.setGridColor(java.awt.Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        ldireccion = new javax.swing.JLabel();
        lnombres = new javax.swing.JLabel();
        lapellidos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        ltelefono = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        lemail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        nombres = new javax.swing.JTextField();
        borrar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        ListarCiudades = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListarId = new javax.swing.JButton();
        idInicio = new javax.swing.JTextField();
        idFin = new javax.swing.JTextField();
        BuscarNombre = new javax.swing.JButton();
        BuscarApellido = new javax.swing.JButton();
        BuscarId = new javax.swing.JButton();
        idBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Agenda Telefónica");

        ldireccion.setText("Dirección:");

        lnombres.setText("Nombres:");

        lapellidos.setText("Apellidos:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Teléfono", "Dirección", "Email"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        ltelefono.setText("Teléfono:");

        lemail.setText("Email:");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        ListarCiudades.setText("Listar Contactos");
        ListarCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCiudadesActionPerformed(evt);
            }
        });

        jLabel1.setText("Listar contactos por ciudad");

        jLabel2.setText("Listar contactos por rango");

        ListarId.setText("Listar Contactos");
        ListarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarIdActionPerformed(evt);
            }
        });

        BuscarNombre.setText("Buscar por nombre");
        BuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNombreActionPerformed(evt);
            }
        });

        BuscarApellido.setText("Buscar por apellido");
        BuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarApellidoActionPerformed(evt);
            }
        });

        BuscarId.setText("Buscar por id");
        BuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIdActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(ListarCiudades)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idFin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(ListarId))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuscarNombre)
                                    .addComponent(BuscarApellido)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BuscarId)
                                .addGap(21, 21, 21)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lapellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ltelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ldireccion)
                                .addGap(18, 18, 18)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lemail)
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(editar)
                                .addGap(31, 31, 31)
                                .addComponent(borrar)
                                .addGap(8, 8, 8)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(lnombres)
                    .addContainerGap(573, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(titulo)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lapellidos)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltelefono)
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ldireccion)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lemail)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(consultar)
                            .addComponent(borrar)
                            .addComponent(editar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BuscarNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarApellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cerrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarCiudades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListarId)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(lnombres)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        Connection con = conectar();
        if (con != null) {
            if (!nombres.getText().isEmpty()
                    && !apellidos.getText().isEmpty()
                    && !telefono.getText().isEmpty()
                    && !direccion.getText().isEmpty()
                    && !email.getText().isEmpty()) {
                String query = "INSERT INTO datos(id,nombres,apellidos,telefono,direccion,email) VALUES (null,'" + nombres.getText() + "','" + apellidos.getText() + "','" + telefono.getText() + "','" + direccion.getText() + "','" + email.getText() + "');";
                try {
                    //preparo la consulta
                    PreparedStatement preparar = con.prepareStatement(query);
                    //ejecuto la consulta luego de prepararla, cuando la consulta es insert, update, delete etc, devuelve un entero con el número de filas afectadas
                    preparar.executeUpdate();
                    salida.setText("Consulta correcta");
                } catch (SQLException ex) {
                    salida.setText("Error en la consulta");
                }
            } else {
                salida.setText("No hay datos.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        //limpio la tabla antes de llevar los valores
        modelo.setRowCount(0);
        Connection con = conectar();
        String query = "SELECT * FROM datos;";
        try {
            //preparo la consulta
            PreparedStatement preparar = con.prepareStatement(query);
            //ejecuto la consulta luego de prepararla, como es un select devuelve una lista de tipo ResultSet
            ResultSet resultado = preparar.executeQuery();
            //hago un ciclo para recorrer la lista y ponerla en la tabla de la interfaz
            while (resultado.next()) {
                modelo.addRow(new Object[]{resultado.getInt("id"), resultado.getString("nombres"), resultado.getString("apellidos"), resultado.getString("direccion"), resultado.getString("telefono"), resultado.getString("email")});
            }
        } catch (SQLException ex) {
            System.out.println("Error en el sql");
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        Connection con = conectar();
        if (con != null) {
            if (!email.getText().isEmpty()) {
                String query = "DELETE FROM datos WHERE email = '" + email.getText() + "';";
                try {
                    // preparo la consulta
                    PreparedStatement preparar = con.prepareStatement(query);
                    // ejecuto la consulta
                    preparar.executeUpdate();
                    salida.setText("Contacto eliminado correctamente.");
                } catch (SQLException ex) {
                    salida.setText("Error al eliminar el contacto.");
                }
            } else {
                salida.setText("No hay email.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        Connection con = conectar();
        if (con != null) {
            if (!nombres.getText().isEmpty()
                    && !apellidos.getText().isEmpty()
                    && !telefono.getText().isEmpty()
                    && !direccion.getText().isEmpty()
                    && !email.getText().isEmpty()) {
                String query = "UPDATE datos SET nombres='" + nombres.getText() + "', apellidos='" + apellidos.getText() + "', telefono='" + telefono.getText() + "', direccion='" + direccion.getText() + "' WHERE email='" + email.getText() + "';";
                try {
                    // preparo la consulta
                    PreparedStatement preparar = con.prepareStatement(query);
                    // ejecuto la consulta
                    preparar.executeUpdate();
                    salida.setText("Contacto actualizado correctamente.");
                } catch (SQLException ex) {
                    salida.setText("Error al actualizar el contacto.");
                }
            } else {
                salida.setText("No hay datos para actualizar.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_editarActionPerformed

    private void ListarCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCiudadesActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        Connection con = conectar();
        if (con != null) {
            if (!direccion.getText().isEmpty()) {
                String query = "SELECT * FROM datos WHERE direccion LIKE '%" + direccion.getText() + "%';";
                try {
                    PreparedStatement preparar = con.prepareStatement(query);
                    ResultSet resultado = preparar.executeQuery();
                    boolean hayDatos = false;
                    while (resultado.next()) {
                        modelo.addRow(new Object[]{
                            resultado.getInt("id"),
                            resultado.getString("nombres"),
                            resultado.getString("apellidos"),
                            resultado.getString("direccion"),
                            resultado.getString("telefono"),
                            resultado.getString("email")
                        });
                        hayDatos = true;
                    }
                    if (hayDatos) {
                        salida.setText("Contactos listados por ciudad correctamente.");
                    } else {
                        salida.setText("No hay contactos en esa ciudad.");
                    }
                } catch (SQLException ex) {
                    salida.setText("Error al listar contactos por ciudad.");
                }
            } else {
                salida.setText("Por favor ingresa una ciudad para buscar.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }

    }//GEN-LAST:event_ListarCiudadesActionPerformed

    private void ListarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarIdActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        Connection con = conectar();
        if (con != null) {
            if (!idInicio.getText().isEmpty() && !idFin.getText().isEmpty()) {
                String query = "SELECT * FROM datos WHERE id BETWEEN " + idInicio.getText() + " AND " + idFin.getText() + ";";
                try {
                    PreparedStatement preparar = con.prepareStatement(query);
                    ResultSet resultado = preparar.executeQuery();
                    boolean hayDatos = false;
                    while (resultado.next()) {
                        modelo.addRow(new Object[]{
                            resultado.getInt("id"),
                            resultado.getString("nombres"),
                            resultado.getString("apellidos"),
                            resultado.getString("direccion"),
                            resultado.getString("telefono"),
                            resultado.getString("email")
                        });
                        hayDatos = true;
                    }
                    if (hayDatos) {
                        salida.setText("Contactos listados por rango de ID correctamente.");
                    } else {
                        salida.setText("No se encontraron contactos en ese rango.");
                    }
                } catch (SQLException ex) {
                    salida.setText("Error al listar por rango de ID.");
                }
            } else {
                salida.setText("Debes ingresar el ID inicial y el ID final.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_ListarIdActionPerformed

    private void BuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNombreActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        Connection con = conectar();
        if (con != null) {
            if (!nombres.getText().isEmpty()) {
                String query = "SELECT * FROM datos WHERE nombres LIKE '%" + nombres.getText() + "%';";
                try {
                    PreparedStatement preparar = con.prepareStatement(query);
                    ResultSet resultado = preparar.executeQuery();
                    boolean hayDatos = false;
                    while (resultado.next()) {
                        modelo.addRow(new Object[]{
                            resultado.getInt("id"),
                            resultado.getString("nombres"),
                            resultado.getString("apellidos"),
                            resultado.getString("direccion"),
                            resultado.getString("telefono"),
                            resultado.getString("email")
                        });
                        hayDatos = true;
                    }
                    if (hayDatos) {
                        salida.setText("Búsqueda por nombre completada.");
                    } else {
                        salida.setText("No se encontraron contactos con ese nombre.");
                    }
                } catch (SQLException ex) {
                    salida.setText("Error al buscar por nombre.");
                }
            } else {
                salida.setText("Por favor ingresa un nombre para buscar.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_BuscarNombreActionPerformed

    private void BuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarApellidoActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        Connection con = conectar();
        if (con != null) {
            if (!apellidos.getText().isEmpty()) {
                String query = "SELECT * FROM datos WHERE apellidos LIKE '%" + apellidos.getText() + "%';";
                try {
                    PreparedStatement preparar = con.prepareStatement(query);
                    ResultSet resultado = preparar.executeQuery();
                    boolean hayDatos = false;
                    while (resultado.next()) {
                        modelo.addRow(new Object[]{
                            resultado.getInt("id"),
                            resultado.getString("nombres"),
                            resultado.getString("apellidos"),
                            resultado.getString("direccion"),
                            resultado.getString("telefono"),
                            resultado.getString("email")
                        });
                        hayDatos = true;
                    }
                    if (hayDatos) {
                        salida.setText("Búsqueda por apellido completada.");
                    } else {
                        salida.setText("No se encontraron contactos con ese apellido.");
                    }
                } catch (SQLException ex) {
                    salida.setText("Error al buscar por apellido.");
                }
            } else {
                salida.setText("Por favor ingresa un apellido para buscar.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_BuscarApellidoActionPerformed

    private void BuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIdActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        Connection con = conectar();
        if (con != null) {
            if (!idBuscar.getText().isEmpty()) {
                String query = "SELECT * FROM datos WHERE id = " + idBuscar.getText() + ";";
                try {
                    PreparedStatement preparar = con.prepareStatement(query);
                    ResultSet resultado = preparar.executeQuery();
                    boolean hayDatos = false;
                    while (resultado.next()) {
                        modelo.addRow(new Object[]{
                            resultado.getInt("id"),
                            resultado.getString("nombres"),
                            resultado.getString("apellidos"),
                            resultado.getString("direccion"),
                            resultado.getString("telefono"),
                            resultado.getString("email")
                        });
                        hayDatos = true;
                    }
                    if (hayDatos) {
                        salida.setText("Contacto encontrado por ID.");
                    } else {
                        salida.setText("No existe ningún contacto con ese ID.");
                    }
                } catch (SQLException ex) {
                    salida.setText("Error al buscar por ID.");
                }
            } else {
                salida.setText("Por favor ingresa un ID para buscar.");
            }
        } else {
            salida.setText("Error conexión incorrecta.");
        }
    }//GEN-LAST:event_BuscarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarApellido;
    private javax.swing.JButton BuscarId;
    private javax.swing.JButton BuscarNombre;
    private javax.swing.JButton ListarCiudades;
    private javax.swing.JButton ListarId;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton borrar;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idBuscar;
    private javax.swing.JTextField idFin;
    private javax.swing.JTextField idInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lapellidos;
    private javax.swing.JLabel ldireccion;
    private javax.swing.JLabel lemail;
    private javax.swing.JLabel lnombres;
    private javax.swing.JLabel ltelefono;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextArea salida;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
